spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  jpa:
    ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQL9Dialect
       hbm2ddl.auto: update
       use_sql_comments: true
       format_sql: false
       show_sql: true
       max_fetch_depth: 5
       jdbc:
         fetch_size: 50
         batch_size: 10
         lob.non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

#
external:
  ses:
    url: http://localhost:8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

#APP PROPS
order:
  expiredMinutes: 15
cart:
  maxItemsAmount: 3
server:
  port: 8888

manager:
  email: info@titsonfire.store

