DELETE FROM CUSTOMER CASCADE;
DELETE FROM SHOPPING_CART CASCADE;
DELETE FROM COMMODITY_BRANCH_ATTRIBUTE_SET CASCADE;
DELETE FROM COMMODITY_BRANCH;
DELETE FROM COMMODITY_IMAGE CASCADE;
DELETE FROM COMMODITY;
DELETE FROM commodity_attribute_value CASCADE;
DELETE FROM commodity_attribute;
DELETE FROM commodity_type;