package ru.maxmorev.restful.eshop.entities;

public interface Constants {

    String ID_GENERATOR_COMMODITY = "ID_GENERATOR_COMMODITY";
    String ID_GENERATOR_COMMODITY_SEQUENCE_NAME = "RES_SEQUENCE_COMMODITY";

    String ID_GENERATOR_ATTRIBUTE = "ID_GENERATOR_ATTRIBUTE";
    String ID_GENERATOR_ATTRIBUTE_SEQUENCE_NAME = "RES_SEQUENCE_ATTRIBUTE";

    String ID_GENERATOR_ATTRIBUTE_VALUE = "ID_GENERATOR_ATTRIBUTE_VALUE";
    String ID_GENERATOR_ATTRIBUTE_VALUE_SEQUENCE_NAME = "RES_SEQUENCE_ATTRIBUTE_VALUE";

    String ID_GENERATOR_BRANCH = "ID_GENERATOR_BRANCH";
    String ID_GENERATOR_BRANCH_SEQUENCE_NAME = "RES_SEQUENCE_BRANCH";

    String ID_GENERATOR_BRANCH_ATTRIBUTE_SET = "ID_GENERATOR_ATTRIBUTE_SET";
    String ID_GENERATOR_BRANCH_ATTRIBUTE_SET_SEQUENCE_NAME = "RES_SEQUENCE_ATTRIBUTE_SET";

    String ID_GENERATOR_COMMODITY_TYPE = "ID_GENERATOR_COMMODITY_TYPE";
    String ID_GENERATOR_COMMODITY_TYPE_SEQUENCE_NAME = "RES_SEQUENCE_COMMODITY_TYPE";

    String ID_GENERATOR_CUSTOMER = "ID_GENERATOR_CUSTOMER";
    String ID_GENERATOR_CUSTOMER_SEQUENCE_NAME = "RES_SEQUENCE_CUSTOMER";

    String ID_GENERATOR_ORDER = "ID_GENERATOR_ORDER";
    String ID_GENERATOR_ORDER_SEQUENCE_NAME = "RES_SEQUENCE_ORDER";

    String ID_GENERATOR_SHOPPING_CART = "ID_GENERATOR_SHOPPING_CART";
    String ID_GENERATOR_SHOPPING_CART_SEQUENCE_NAME = "RES_SEQUENCE_SHOPPING_CART";

    String ID_GENERATOR_SHOPPING_CART_SET = "ID_GENERATOR_SHOPPING_CART_SET";
    String ID_GENERATOR_SHOPPING_CART_SET_SEQUENCE_NAME = "RES_SEQUENCE_SHOPPING_CART_SET";


}
